### ISSUE TITLE
wait timer for likes

### ISSUE THREAD

**Issue by zzeesstt** [ricardojoserf/instagram-liker-all-posts#1]
Hi guys.
Great script!  It's a pity there is not enough lat timing for the likes.
wait = 10 * 60
Please tell me how to add it?

**Comment by ricardojoserf** [comment]
Hi zzeesstt! I added a variable in main.py for adding a delay between likes. It is set to 10 seconds, you can change it to whatever you want, just pull the project and i hope it is solved ;)

Ricardo

**Comment by zzeesstt** [comment]
Oh .... Yes, I even almost guessed right)))
Only instead of "delay_seconds = 10" wrote "wait = 5 * 60" and
"time.sleep (wait)" and it did not work (((
Thank you so much!

**Comment by ricardojoserf** [comment]
You are welcome :)

Ricardo
